apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars-server
  template:
    metadata:
      labels:
        app: cars-server
    spec:
      containers:
        - name: cars-server
          image: sever_for_cars:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cars-server
spec:
  type: NodePort
  selector:
    app: cars-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
