apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  parallelism: 3
  completions: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:1.1.0
        command: ["k6", "run", "/scripts/main.js"]
        env:
          - name: BASE_URL
            value: "http://cars-api.default.svc.cluster.local:8000"
          - name: TOTAL_VUS
            value: "10"
        volumeMounts:
          - name: scripts
            mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: k6-scripts
