apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: cars-load-test
spec:
  parallelism: 3        # 3 POD'–ê
  script:
    # For configMap test configuration 
    # configMap:
    #   name: k6-scripts
    #   file: main.js
    localFile: /scripts/main.js

  runner:
    image: server_for_k6:1.0.2
    imagePullPolicy: IfNotPresent # Don't try to pool image from a repository
  

  arguments: "-e BASE_URL=http://cars-server:8000 -e TOTAL_VUS=10 -e WARMUP_SEC=10 -e STEADY_SEC=60 -e COOLDOWN_SEC=10"
  

  