apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics:latest
          args:
            - "-retentionPeriod=14d"
            - "-storageDataPath=/storage"
          ports:
            - name: http
              containerPort: 8428
          volumeMounts:
            - name: data
              mountPath: /storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: victoria-metrics-data
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: default
spec:
  type: NodePort
  selector:
    app: victoria-metrics
  ports:
    - name: http
      port: 8428
      targetPort: 8428
      nodePort: 30028
