apiVersion: v1
kind: PersistentVolume
metadata:
  name: vm-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    # Windows host path inside Docker Desktop VM (WSL2)
    path: /run/desktop/mnt/host/c/k8s_external_disk/victoria_metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
